/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 04.05.2026 13:47:22

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1456;
#else
constexpr int kTensorArenaSize = 432;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,91 } };
const TfArray<1, float> quant0_scale = { 1, { 1.2533785104751587, } };
const TfArray<1, int> quant0_zero = { 1, { -120 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[10] = { 59, 21, -83, 271, 302, 293, -175, -184, -93, -74, };
const TfArray<1, int> tensor_dimension1 = { 1, { 10 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00031861217576079071, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[10*10] = { 
  74, -62, -96, 61, 68, 2, -92, -38, 34, 40, 
  54, 12, -83, -16, 95, -106, 56, -79, -76, 68, 
  -84, -32, -92, 113, 49, 94, 91, -91, 107, 15, 
  16, -127, -53, -50, -35, -14, 109, 16, 74, -105, 
  67, -118, -115, 57, -31, 20, -26, -127, -88, -58, 
  -13, 21, 6, -87, -6, -58, 71, -111, -12, 33, 
  90, 1, 98, 42, 36, 0, 101, -14, 51, 3, 
  -31, -111, 75, 16, 29, 24, 14, 116, -85, 77, 
  103, 67, -18, -67, -61, 37, 50, 64, -82, -79, 
  -83, 48, 23, -101, 78, 80, 23, 106, 25, -1, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 10,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0048937518149614334, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { -25, 28, -21, -23, 57, -29, -23, -29, -2, -30, };
const TfArray<1, float> quant3_scale = { 1, { 0.001009288476780057, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  42, -81, -84, 11, 93, 10, 108, -121, -17, -63, 13, 11, 61, 110, 45, -96, -2, -28, -87, 24, 
  -65, -120, 85, 68, 47, -31, -65, -111, -104, 22, -51, -63, 67, 49, 62, 94, -36, 36, -36, -47, 
  -30, -101, -10, 111, -53, -68, -40, 17, -46, -18, 31, 50, -29, -96, -16, -73, 82, -102, -105, -86, 
  61, 14, 91, 7, -73, 73, -61, -54, -34, 66, 100, 55, -85, -106, -10, -35, -32, -56, 106, 106, 
  -34, 63, -83, -42, -75, 82, -26, 26, -87, 85, 106, 72, -4, 45, 44, -91, -46, 106, 94, 40, 
  -94, 74, -78, 53, -36, -118, -10, 75, -127, -49, 77, 62, -53, 59, -29, -61, -47, 65, -71, -1, 
  91, 50, -66, -84, 78, 80, 5, -40, -34, -6, 61, 36, -81, -47, 3, -14, 59, -19, -19, -41, 
  -21, 95, 52, 61, -21, 91, 82, -123, 113, -38, -73, 110, 62, -24, -115, 43, 96, 6, 10, 101, 
  61, 43, 51, 44, 86, 40, -116, -34, -37, 25, 95, 32, 6, -116, -41, 110, -105, 74, -41, -36, 
  49, -75, -27, 0, 75, 108, -28, 1, 72, -93, -72, 57, -74, -66, 50, -16, -31, 93, 4, 77, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0036444116849452257, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { -6, 0, 7, -5, -13, -15, -17, 8, -2, 11, 2, -5, 6, 10, 2, 4, 0, 0, 1, 2, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.0029318640008568764, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*91] = { 
  -10, -14, -13, 78, 34, 57, 37, -54, 36, -69, 6, 44, -83, -71, -5, 83, 13, 56, -47, -46, 86, -24, 82, 18, -89, 64, -52, -36, -63, -99, 14, 31, 62, -77, -88, 44, -58, 74, -5, -66, 45, -27, -78, -31, -94, 74, -43, 84, -70, -76, -25, -92, 26, -7, -90, 57, 88, 77, 101, 62, 42, -35, 15, -64, -10, -58, 12, 30, 70, -21, 28, -77, -55, -20, -15, -47, 73, 50, -20, 65, 25, -11, -20, 35, -14, 18, -94, -6, -69, -87, 38, 
  -96, -7, 80, 12, -29, 16, 31, 29, 43, 90, -63, 41, 13, 18, 60, -53, 76, 48, 99, -59, -16, -10, 81, -19, 50, 47, -18, 71, -24, -72, -15, 91, 84, 95, 67, -31, -78, -9, 26, -44, -41, -54, 95, 69, 56, -26, 72, -68, 8, 0, -89, -11, 4, -37, -13, -99, -93, 78, 82, -78, -17, 67, -40, -17, -24, 1, 74, -97, 54, -26, 88, -56, 58, -6, 14, 80, -31, -55, -7, 87, -13, -98, -50, -1, 45, 7, -20, -71, 19, -24, 31, 
  78, -13, -82, -66, 40, -50, 62, 84, 102, -7, -73, 17, -63, 64, -73, 65, 37, 60, -8, 29, 88, -107, 43, -91, -1, -34, 107, 34, -61, -69, -40, 43, 34, -90, -38, -50, -103, -20, 41, -71, 20, 69, -94, -23, 19, -28, -63, -95, 19, -43, 34, -40, -7, 4, 69, -91, -9, -2, 0, -38, 82, -42, -24, 7, -36, 77, -7, -44, -41, -52, -15, -104, 1, 77, -23, -90, -90, 46, -47, -39, 44, -56, 19, -20, -6, 3, -38, -14, -90, -11, -80, 
  -84, 45, -47, 52, -12, 59, -6, 98, 55, -79, 84, 82, 54, 57, 46, -28, -81, -41, 34, 63, -64, 40, -64, -38, 58, 48, -74, 55, 75, 58, -38, 39, 79, -46, 57, 10, 94, -96, 17, 60, -80, 58, -6, 69, 87, -83, -11, -58, 51, 39, -71, 0, -23, -92, 17, -82, -88, -90, -33, -5, 95, 40, 99, 77, -58, -92, 50, -92, -64, -82, 63, -45, -46, -63, 28, 40, -17, 105, 28, 91, 12, 66, 62, -25, -14, -74, -3, -33, 65, -35, 44, 
  64, 8, 22, -79, -93, -76, 84, -22, -35, 61, -24, 22, -50, -61, -51, 33, 46, 55, -9, -19, -7, 97, -15, -11, -27, 11, 54, 80, -108, -92, 34, -74, 87, -68, -23, -45, -25, -85, 30, 40, 29, 14, -102, -51, 36, -81, 53, 68, -37, 52, 44, 80, -94, -27, -44, 79, 50, 88, 98, 70, -72, -66, 102, 103, 18, 39, -47, 75, -103, -31, -74, 37, 78, 45, 51, 57, -21, -16, -67, -56, 48, -103, 45, -60, 42, -47, 30, -61, 75, -25, -27, 
  -34, 62, 30, -19, -37, -64, 25, 113, -20, 37, -76, -20, -79, 29, 24, -11, -113, 2, -37, 5, -77, -80, -12, -51, 68, -23, 5, -15, -51, 75, -37, -25, 72, -62, 22, -94, 67, -54, 45, 70, 60, 25, -87, -40, -13, -127, -105, -76, -36, 28, 51, -22, 10, -26, 30, 38, 19, -13, 58, 11, 33, -87, 71, -71, -19, -6, -40, 72, 59, 17, 98, -36, 76, -62, -87, -52, -1, -5, 45, -11, -89, 17, -64, 81, -2, -68, 36, 2, 105, -8, 21, 
  39, -36, -29, -70, -57, -80, -15, 87, -15, 26, 14, 11, 20, 37, 48, -36, -51, -43, 84, 64, -58, 11, -55, 54, -51, -20, 81, -62, 61, 3, 59, -102, -8, -17, -81, 56, -88, 41, -78, 76, 11, 4, -26, -3, -70, -106, 73, -63, -29, -38, -83, 73, -107, 57, 10, -26, 12, 83, 54, -32, -57, 15, 74, -53, 55, 3, -73, 41, -76, -38, 20, 87, -30, 47, 30, 60, 50, 83, 23, -48, 55, 44, 21, 32, -52, -23, 66, 32, -37, -33, -61, 
  90, -88, 31, 93, 94, 45, 46, 58, -7, 101, -2, 114, -10, 51, -75, -67, -36, -54, -62, 98, 88, -54, -43, 7, -12, 104, -18, 28, -72, -16, 9, 94, 27, -81, -32, -86, -13, 29, 68, -24, -34, 42, 105, 99, 43, 1, 32, -80, -46, 61, -55, -25, -3, 6, -7, -57, -83, 62, 60, -101, -68, -36, 48, -74, 51, 39, 18, -14, -55, 78, -62, 16, -19, 38, -3, 16, -38, 54, -30, 54, 120, -101, 47, -2, 27, -92, 43, 44, 66, -34, -24, 
  53, 103, 65, -21, -92, 57, -14, -61, -3, -19, 5, 57, 63, -49, 12, -51, 41, -43, 82, 3, 75, 56, 72, 27, 40, 50, 53, -9, 74, -85, 60, -115, -38, -21, -88, -44, -97, 66, -71, 11, -42, -55, -88, -34, -90, 21, -45, -25, -61, 17, -100, -110, 90, -48, 31, 48, 15, 39, -22, -46, 54, -31, 74, -50, -3, -100, 92, 68, 66, -49, -47, -37, 7, -86, -39, -96, -78, -52, -53, 98, -47, -56, -68, -46, 80, 18, -7, 33, 54, 50, -4, 
  -87, 40, -99, -11, -72, 42, -106, -17, -67, -115, -100, -84, -112, -5, -75, 97, -16, 37, 84, -48, -7, 75, 31, 104, 111, 79, 26, 9, 15, 46, -58, -12, -57, 10, 82, 41, 77, 85, -4, 24, 11, 50, -44, 20, -28, -85, 74, 49, 91, -71, 57, 101, -72, -78, -39, 17, 40, 20, -78, 40, -77, -45, -58, 81, 9, 0, -91, -6, -86, 20, -51, 78, 99, 16, -4, -61, 102, -18, -76, 70, 73, 86, -108, -44, -58, 87, -55, -42, 57, 27, 87, 
  87, 14, 38, -91, -74, -44, 51, 10, -21, 27, -82, 23, 11, -53, 50, -51, -2, -7, 58, 44, -62, 63, -70, 95, 102, 0, -27, -42, 78, 69, -95, -52, -53, 1, 114, 106, -12, -58, -62, 33, 31, -16, 8, -32, -20, 87, 27, -79, 75, 60, -16, -47, 1, -4, 78, 90, -63, -23, 41, 1, 40, 49, 80, 81, 38, -72, -86, 50, 40, 21, 93, 29, -4, -23, 17, 105, 42, -47, 60, 101, -25, -76, 24, -52, -29, 79, -23, 38, -25, -38, 10, 
  -23, 24, 82, -36, -78, -92, 94, -42, 71, -26, 82, 88, 61, 86, -28, 45, -52, -38, 88, 5, -17, -17, 99, 12, 41, 46, 56, 40, 97, 29, -19, -25, 10, -38, 29, -21, -69, 23, 29, 48, 31, 72, 77, -24, -57, -34, 21, 52, -86, -8, -77, 77, 24, 34, 78, 54, 50, -14, 15, -75, 77, 55, 0, -23, 73, 57, 69, -25, -33, -23, -70, 11, -46, -52, 87, 35, 49, 87, 41, 8, 41, 74, -78, -51, -88, -81, -57, 50, -8, 70, 57, 
  -42, -91, -6, -29, 56, -92, -66, -103, -87, 41, -30, -98, 17, 37, -32, 59, 38, -4, 68, -41, 31, 41, -74, 49, 37, -45, -9, -32, 69, -8, -24, 9, -111, 73, 46, 48, 65, -79, -98, -69, -5, 22, -79, -48, -105, -47, 86, 52, -18, 95, 63, -92, -114, 0, -70, -87, -54, 12, -37, 25, -51, -89, -94, 49, -1, 6, 50, 25, 37, 91, -18, -67, 25, 43, 6, -118, -58, 57, -100, -77, 0, 68, 103, 44, 72, 55, -109, -76, -15, 41, -88, 
  23, -95, -59, 9, 102, 94, -89, 88, -39, 18, 12, 21, 61, 19, -16, -71, -80, 3, -88, -46, -87, -89, -16, -42, -51, -111, -56, 97, -16, 25, 48, -85, -77, -99, -24, 23, 42, -5, 76, -15, 107, 42, 102, -49, 110, -24, 19, 54, 122, 78, 56, 46, -84, -40, 81, -17, 40, 56, 36, -32, -16, -49, -33, -91, 49, 62, 87, 69, 41, 118, -97, -36, 45, -36, 30, -88, -69, -60, 39, -39, -39, 65, -6, -47, 38, -1, 56, 69, -20, -112, -9, 
  74, -71, -50, 7, -7, -69, -54, 23, 36, 22, 85, -108, -95, 89, -96, -44, -84, 8, 65, -69, 88, 103, -44, 78, -86, -52, -26, -80, 82, -23, 97, -42, -38, 66, -7, -61, -71, 25, 85, -95, -66, 65, -90, 59, -1, 68, -29, -51, -89, -34, -12, 55, 53, -27, -68, -59, 88, -12, 96, -46, 15, 50, -50, 97, 22, 97, 101, 61, -6, 67, 19, -52, 96, -33, 92, 53, -35, 31, 8, 12, 52, 19, -59, -38, 25, -73, 80, 14, -76, 24, -40, 
  0, 82, -79, -98, -106, 16, -22, 6, 33, 23, -16, 28, -59, 51, 40, 80, 14, 41, 41, 67, -80, 92, -69, 54, 33, 12, -40, -43, -12, -48, 28, -29, -29, 61, 0, 28, 10, -84, 32, 80, 65, -37, 24, -81, 55, -73, -104, -25, -86, 58, 29, -7, 72, 84, 47, -56, 80, 38, -76, 79, 1, -64, 16, -44, 14, 43, 17, -53, 12, 59, -89, 76, 75, 79, 35, 67, -44, 22, 93, 51, -65, -60, 4, 93, 101, 84, 20, 59, 61, 103, 2, 
  21, -61, -36, 0, 92, -10, -20, -59, 47, -74, -74, -19, 33, 26, -38, 35, -80, -43, 26, -47, -96, -68, 25, -53, 29, -43, -28, 90, -74, 67, 32, -19, 63, -72, -42, -64, 18, -95, -55, 4, -13, -13, 17, 80, -28, -101, 55, -103, -26, -56, -8, -23, -44, -80, -26, -91, -5, -36, 48, -83, -76, 71, -72, -7, -81, 19, -6, -45, -2, 101, -95, -33, -64, 72, 60, 38, -58, 16, -79, 15, 8, 90, -90, -46, -19, 54, -6, -72, 82, -34, 2, 
  -19, 49, 88, 70, 72, -31, -38, 82, 34, -13, -35, 96, -35, 70, -71, -33, -69, 26, 91, -54, 53, -42, -73, 97, -53, -77, -50, 32, -7, -57, -13, -75, 3, 24, 9, 97, 94, -53, 69, -83, -93, -29, 99, -30, 29, -65, 9, 94, -75, 48, -46, -57, 91, 52, 29, -73, 74, -86, -22, -47, 30, -77, 48, 93, -20, 52, -11, 2, 32, -28, 76, -36, 63, 90, 46, 24, -80, -73, 72, -76, -80, -90, -87, 17, 51, 92, -38, 23, 22, 43, -2, 
  -87, -29, 50, -100, 42, 4, -68, -13, -4, -39, -95, -42, -86, -61, -82, -47, -10, -87, -55, 36, -51, 76, -64, 67, -55, -91, 3, -43, -95, -66, 52, -46, -70, -100, 85, 62, 15, -78, -83, -24, -89, 19, -63, 43, -6, -18, 89, 6, -92, -107, -10, -101, 57, -35, 69, -79, -76, -55, -20, 78, -24, -43, -57, 81, 52, -35, 74, -70, -15, 70, 68, 62, 83, -34, -82, 40, 97, 25, -22, 42, 36, 29, 70, 0, 50, 20, 86, 11, -4, -77, -93, 
  -13, 80, -2, -54, -26, -44, 17, -25, 57, 55, -92, 66, 54, -9, -17, -50, -18, -104, -77, 2, -61, -107, 51, -102, -36, -17, -73, -48, 20, 71, -79, -11, 58, -86, -10, 9, -111, -5, -13, -19, -50, -100, 23, 53, -24, -110, -122, -5, -40, -29, -7, 13, -89, 12, 24, -57, 46, -98, -80, 69, -85, 55, -82, 23, -82, -15, -4, -71, -84, -72, -106, 58, -38, -20, -29, 26, -91, -106, -90, -38, 80, -17, -12, -95, -27, 27, 79, -19, 21, -7, -99, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,91 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0023391689173877239, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.27694138884544373, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.065105915069580078, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<1, float> quant9_scale = { 1, { 0.089145883917808533, } };
const TfArray<1, int> quant9_zero = { 1, { 22 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 91, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 100, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 1820, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 96), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_982154_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_982154_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_982154_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_982154_3_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_982154_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
