export const ipcChannels = {
	serialListPorts: 'sensenode:serial:list-ports',
	serialConnect: 'sensenode:serial:connect',
	serialDisconnect: 'sensenode:serial:disconnect',
	serialPause: 'sensenode:serial:pause',
	serialResume: 'sensenode:serial:resume',
	deviceFrame: 'sensenode:device:frame',
	serialLine: 'sensenode:serial:line',
	dataSourceStatus: 'sensenode:datasource:status',
	appShowMainWindow: 'sensenode:app:show-main-window',
	appSetLocale: 'sensenode:app:set-locale',
	eventNotifyStable: 'sensenode:event:notify-stable',
	eventLogsList: 'sensenode:event:logs:list',
	eventLogsAdd: 'sensenode:event:logs:add',
	eventTasksList: 'sensenode:event:tasks:list',
	eventTasksUpsert: 'sensenode:event:tasks:upsert',
	eventTasksRemove: 'sensenode:event:tasks:remove',
} as const
